# -*- coding: utf-8 -*-
"""Anime Recommendations Project 🎇

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/anime-recommendations-project-b247d467-0570-48b8-b0a5-719ae0a3b8ec.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20240605/auto/storage/goog4_request%26X-Goog-Date%3D20240605T145705Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D89e85619ce96ab6beb07b84266ceab922253559e09f98e4a1f7874b2272e04563d17fda2de9e7db65c65e42b8bd0599535fe25a39c15894d0006511935e69920a58c6f7d3ba7534ce42cdcaac8ff52ec01ef13a04068b765e1b749355b089e8c84f6d8dc3bf993305e1b544e1ee14c91ff7b5f707f457d3121ffab81ef2617a9fbbe9aa11e8aa7d597c81d6dfc5a3c0edf6406a38068fbec2181cd123f6e3a76826f33283190fc7a2dc8cecb7df7fae17c7388d83592b1a645b98584b847abb9ed3cf62c9e43d9e99ca3f82ad50994cdbe3dc73684fba07d024462ee751cbdbb4d631954d827ec41192d7a5bc291d560dd794ae109bf501600fce6cc361238f0
"""

import os
import sys
from tempfile import NamedTemporaryFile
from urllib.request import urlopen
from urllib.parse import unquote, urlparse
from urllib.error import HTTPError
from zipfile import ZipFile
import tarfile
import shutil

CHUNK_SIZE = 40960
DATA_SOURCE_MAPPING = 'anime-recommendations-database:https%3A%2F%2Fstorage.googleapis.com%2Fkaggle-data-sets%2F571%2F1094%2Fbundle%2Farchive.zip%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com%252F20240605%252Fauto%252Fstorage%252Fgoog4_request%26X-Goog-Date%3D20240605T145705Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D5c147acc5b1d9a892c86abd4aecf958b7d38e821c3b276557a9c1667223fc3d05c391b50b7a103ba7da4468c69ee492e3167e9a50c83c8ed5bd13541f951f5ff42a9186e5bf7cb2b3f864a6eafd7ea64f8e128a155445425fd50a68bba84b28d7f73de46f27cdac144a221a721d02797f82c3c741d11909833fd81c7b30a167f72ac946418ff88583292d2b54a2cbd8e638f5ef5f0a71f9d38ac035927ac95908138ff1d1bc4b9b3accf53edc1250fbf82006f2df5032602f362b9587ea2ba7ad2d9ac5e435b2bd2ce5cc591c2c2cfe791f764fce27721d6b20ff023e54634e9bd32caee32b9dd561cde24c198d30831f844a8634529563a180f7baca827cb72'

KAGGLE_INPUT_PATH='/kaggle/input'
KAGGLE_WORKING_PATH='/kaggle/working'
KAGGLE_SYMLINK='kaggle'

!umount /kaggle/input/ 2> /dev/null
shutil.rmtree('/kaggle/input', ignore_errors=True)
os.makedirs(KAGGLE_INPUT_PATH, 0o777, exist_ok=True)
os.makedirs(KAGGLE_WORKING_PATH, 0o777, exist_ok=True)

try:
  os.symlink(KAGGLE_INPUT_PATH, os.path.join("..", 'input'), target_is_directory=True)
except FileExistsError:
  pass
try:
  os.symlink(KAGGLE_WORKING_PATH, os.path.join("..", 'working'), target_is_directory=True)
except FileExistsError:
  pass

for data_source_mapping in DATA_SOURCE_MAPPING.split(','):
    directory, download_url_encoded = data_source_mapping.split(':')
    download_url = unquote(download_url_encoded)
    filename = urlparse(download_url).path
    destination_path = os.path.join(KAGGLE_INPUT_PATH, directory)
    try:
        with urlopen(download_url) as fileres, NamedTemporaryFile() as tfile:
            total_length = fileres.headers['content-length']
            print(f'Downloading {directory}, {total_length} bytes compressed')
            dl = 0
            data = fileres.read(CHUNK_SIZE)
            while len(data) > 0:
                dl += len(data)
                tfile.write(data)
                done = int(50 * dl / int(total_length))
                sys.stdout.write(f"\r[{'=' * done}{' ' * (50-done)}] {dl} bytes downloaded")
                sys.stdout.flush()
                data = fileres.read(CHUNK_SIZE)
            if filename.endswith('.zip'):
              with ZipFile(tfile) as zfile:
                zfile.extractall(destination_path)
            else:
              with tarfile.open(tfile.name) as tarfile:
                tarfile.extractall(destination_path)
            print(f'\nDownloaded and uncompressed: {directory}')
    except HTTPError as e:
        print(f'Failed to load (likely expired) {download_url} to path {destination_path}')
        continue
    except OSError as e:
        print(f'Failed to load {download_url} to path {destination_path}')
        continue

print('Data source import complete.')

"""<h2 style='text-align:center;font-family:Comic Sans MS;font-size:40px;background-color:lightseagreen;border:20px;color:white'>Anime Recommendations<h2>

![](https://i.pinimg.com/originals/a8/be/b0/a8beb06c120be3358360ae2be20588fd.gif)
    
<h2 style='text-align:center;font-family:Comic Sans MS;font-size:30px;background-color:lightseagreen;border:30px;color:white'>table of contents<h2>

## 1. Introduction
## 2. Data Id
## 3. Libraries
## 4. Preprocessing and Data Analysis
## 5. Cosine Similarity Model
## 6. Conclusion

# Introduction

This data set contains information on user preference data from 73,516 users on 12,294 anime. Each user is able to add anime to their completed list and give it a rating and this data set is a compilation of those ratings. The data was scraped thanks to [myanimelist.net](https://myanimelist.net) API.

![](https://i.pinimg.com/originals/a0/ee/ab/a0eeabadf50400a7ebd09ca29efc97db.gif)

# Data Id 📋

## Anime Dataset

This dataset is named **anime**. The dataset contains a set of **12,294 records** under **7 attributes**:

| Column Name | Description                                                    |
|-------------|----------------------------------------------------------------|
| `anime_id`  | myanimelist.net's unique id identifying an anime.              |
| `name`      | full name of anime.                                            |
| `genre`     | comma separated list of genres for this anime.                 |
| `type`      | movie, TV, OVA, etc.                                           |
| `episodes`  | how many episodes in this show. (1 if movie).                  |
| `rating`    |  average rating out of 10 for this anime.                      |
| `members`   | number of community members that are in this anime's "group".  |
                                                


## Rating Dataset

This dataset is named **rating**. The dataset contains a set of **7,813,737 records** under **3 attributes**:

| Column Name | Description                                                                        |
|-------------|------------------------------------------------------------------------------------|
| `user_id`   | non identifiable randomly generated user id.                                       |
| `anime_id`  | the anime that this user has rated.                                                |
| `rating`    | rating out of 10 this user has assigned (-1 if the user watched without assigning) |


### Aim of the Notebook:
Building a better anime recommendation system based only on similiar anime.

![](https://miro.medium.com/max/1080/1*nq3tr7RFPqyoij72F8dnAw.gif)

# Libraries 📙📘📗📕
"""

import os #paths to file
import numpy as np # linear algebra
import pandas as pd # data processing
import warnings# warning filter
import scipy as sp #pivot egineering


#ML model
from sklearn.metrics.pairwise import cosine_similarity


#default theme and settings
pd.options.display.max_columns

#warning hadle
warnings.filterwarnings("always")
warnings.filterwarnings("ignore")

"""# Preprocessing and Data Analysis 💻
## First look at the data
### File Paths 📂
"""

#list all files under the input directory
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

rating_path = "/kaggle/input/anime-recommendations-database/rating.csv"
anime_path = "/kaggle/input/anime-recommendations-database/anime.csv"

"""### First few lines"""

rating_df = pd.read_csv(rating_path)
rating_df.head()

anime_df = pd.read_csv(anime_path)
anime_df.head()

"""### Data shapes and info"""

print(f"anime set (row, col): {anime_df.shape}\n\nrating set (row, col): {rating_df.shape}")

print("Anime:\n")
print(anime_df.info())
print("\n","*"*50,"\nRating:\n")
print(rating_df.info())

"""## Handling missing values 🚫"""

print("Anime missing values (%):\n")
print(round(anime_df.isnull().sum().sort_values(ascending=False)/len(anime_df.index),4)*100)
print("\n","*"*50,"\n\nRating missing values (%):\n")
print(round(rating_df.isnull().sum().sort_values(ascending=False)/len(rating_df.index),4)*100)

"""It seems only the anime dataset has missing values."""

print(anime_df['type'].mode())
print(anime_df['genre'].mode())

"""Weirdly enough the mode value of `genre` is `Hentai`, the mode value of `type` is `TV`.
![](https://media1.tenor.com/images/008c75ee5f61121073f591b008eecec8/tenor.gif?itemid=13249584)
"""

# deleting anime with 0 rating
anime_df=anime_df[~np.isnan(anime_df["rating"])]

# filling mode value for genre and type
anime_df['genre'] = anime_df['genre'].fillna(
anime_df['genre'].dropna().mode().values[0])

anime_df['type'] = anime_df['type'].fillna(
anime_df['type'].dropna().mode().values[0])

#checking if all null values are filled
anime_df.isnull().sum()

"""## Feeture Engineering 🐱‍💻

### Filling Nan values

In general the value `-1` suggests the user did not register a raiting so we will foll with `Nan` values.

"""

rating_df['rating'] = rating_df['rating'].apply(lambda x: np.nan if x==-1 else x)
rating_df.head(20)

"""### Now we will engineer our Dataframe in the following steps:

1. We want to recomment anime series only so the the relevant `type` is `TV`
2. We make a new Dataframe combining both anime and rating on the `anime_id` column.
3. Leaving only `	user_id`, `name` and `rating` as the Df.
4. For computing purpose only we compute our Df based only on the first 7500 users.

"""

#step 1
anime_df = anime_df[anime_df['type']=='TV']

#step 2
rated_anime = rating_df.merge(anime_df, left_on = 'anime_id', right_on = 'anime_id', suffixes= ['_user', ''])

#step 3
rated_anime =rated_anime[['user_id', 'name', 'rating']]

#step 4
rated_anime_7500= rated_anime[rated_anime.user_id <= 7500]
rated_anime_7500.head()

"""### Pivot Table for similarity

We will create a pivot table of users as rows and tv show names as columns. The pivot table will help us will be analized for the calcuations of similarity.
"""

pivot = rated_anime_7500.pivot_table(index=['user_id'], columns=['name'], values='rating')
pivot.head()

"""### Now we will engineer our pivot table in the following steps:

1. Value normalization.
2. Filling `Nan` values as `0`.
3. Transposing the pivot for the next step.
4. Dropping columns with the values of `0` (unrated).
5. Using `scipy` package to convert to sparse matrix format for the similarity computation.

"""

# step 1
pivot_n = pivot.apply(lambda x: (x-np.mean(x))/(np.max(x)-np.min(x)), axis=1)

# step 2
pivot_n.fillna(0, inplace=True)

# step 3
pivot_n = pivot_n.T

# step 4
pivot_n = pivot_n.loc[:, (pivot_n != 0).any(axis=0)]

# step 5
piv_sparse = sp.sparse.csr_matrix(pivot_n.values)

"""# Cosine Similarity Model

![](https://media3.giphy.com/headers/CosineDotRip/dLeMRat9wmuZ.gif)

**formula:**
![](https://cdn-images-1.medium.com/max/579/1*5hJibEtQPavnbgRxg8w2Fg.gif)

Cosine similarity measures the similarity between two vectors of an inner product space. It is measured by the cosine of the angle between two vectors and determines whether two vectors are pointing in roughly the same direction (more on [sciencedirect](https://www.sciencedirect.com/topics/computer-science/cosine-similarity)).
"""

#model based on anime similarity
anime_similarity = cosine_similarity(piv_sparse)

#Df of anime similarities
ani_sim_df = pd.DataFrame(anime_similarity, index = pivot_n.index, columns = pivot_n.index)

def anime_recommendation(ani_name):
    """
    This function will return the top 5 shows with the highest cosine similarity value and show match percent

    example:
    >>>Input:

    anime_recommendation('Death Note')

    >>>Output:

    Recommended because you watched Death Note:

                    #1: Code Geass: Hangyaku no Lelouch, 57.35% match
                    #2: Code Geass: Hangyaku no Lelouch R2, 54.81% match
                    #3: Fullmetal Alchemist, 51.07% match
                    #4: Shingeki no Kyojin, 48.68% match
                    #5: Fullmetal Alchemist: Brotherhood, 45.99% match


    """

    number = 1
    print('Recommended because you watched {}:\n'.format(ani_name))
    for anime in ani_sim_df.sort_values(by = ani_name, ascending = False).index[1:6]:
        print(f'#{number}: {anime}, {round(ani_sim_df[anime][ani_name]*100,2)}% match')
        number +=1

anime_recommendation('Dragon Ball Z')

"""# Conclusion ✔

In this notebook, a recommendation algorithm based on cosine similarity was created.
For further analysis i sugggest prediction based on genres, or a user-user approach (“people like you, like that” logic).

If you liked the notebook please upvote!

![](https://media.tenor.com/images/a5721ade2ad3e7a1a3b45e73b1cd7ed1/tenor.gif)

<h2 style='text-align:center;font-family:Comic Sans MS;font-size:30px;background-color:lightseagreen;border:30px;color:white'>The End<h2>
"""